### ISSUE TITLE
spaces replaced by line break in preview if regex syntax specified in :substitute

### ISSUE THREAD

**Issue by Konfekt** [markonm/traces.vim#21] opened 2018-07-01 14:12 UTC
In any archive, hitting
```vim
:%substitute:\v::cgI<Left><Left><Left><Left><Left>
```
inserts line breaks where spaces are. Same for any other regular expression syntax modifier, such as `\m` or `\V`.

**Comment by markonm** [comment] 2018-07-03 14:25
Is soft wrapping enabled when it happens?

**Comment by Konfekt** [comment] 2018-07-03 15:19
Yes.

**Comment by markonm** [comment] 2018-07-03 15:28
Do you have the same issue when it's turned off?

**Comment by Konfekt** [comment] 2018-07-03 18:50
No.

**Comment by markonm** [comment] 2018-07-03 19:40
This issue is then a duplicate of #18.  Closing.

**Closed as completed by markonm** 2018-07-03 19:40 UTC
